/* VELORA 映堂 catalog — static snapshot of the live app */
(function (global) {
  const VIDEOS = [
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  ];
  const DRAMA = "https://drama-ctg.pages.dev/drama/";
  const NAMES = ["陈可", "周屿", "阿宁", "何蔓", "老白", "Suki", "江澄", "米未", "陆深", "Yuki"];
  const LEARN = [
    "跟完正片完整叙事弧",
    "拆解每集钩子、反转与人物欲望",
    "可对照的分场与走位要点",
    "竖屏/横屏构图差异与近景表演",
    "预留 Drama Engine 成片接入位",
  ];

  const CATEGORIES = [
    { id: "urban", name: "都市情感", blurb: "霓虹、雨夜与说不出口的话", cover: "covers/rooftop.jpg" },
    { id: "mansion", name: "豪门世家", blurb: "合同、替身与看不见的刀", cover: "covers/standin.jpg" },
    { id: "rebirth", name: "穿越重生", blurb: "把错过的那条路再走一遍", cover: "covers/rebirth.jpg" },
    { id: "palace", name: "古装权谋", blurb: "灯火深处，谁先低头", cover: "covers/palace.jpg" },
    { id: "suspense", name: "悬疑刑侦", blurb: "一朵玫瑰，一场审讯", cover: "covers/interrogation.jpg" },
    { id: "office", name: "职场逆袭", blurb: "零点档的灯还亮着", cover: "covers/intern.jpg" },
    { id: "fantasy", name: "奇幻契约", blurb: "北境的雪不认人情", cover: "covers/northsnow.jpg" },
    { id: "campus", name: "校园青春", blurb: "毕业照里少了谁", cover: "covers/campus.jpg" },
  ];

  const INSTRUCTORS = [
    {
      id: "lin-yan",
      name: "林晏",
      title: "短剧导演 · 前院线副导",
      avatar: "instructors/lin-yan.jpg",
      bio: "十年剧组，四年短剧。擅长把一场雨拍成整部戏的呼吸。作品强调场面调度与留白，学员评价“看完会想自己拿起相机”。",
      students: 182400,
      rating: 4.8,
      courseCount: 6,
    },
    {
      id: "su-wan",
      name: "苏晚",
      title: "表演指导 · 影视演员",
      avatar: "instructors/su-wan.jpg",
      bio: "从话剧到竖屏短剧，专注“近景里的真实”。课程拆解对视、停顿和潜台词，帮演员在 9:16 画幅里把情绪做满。",
      students: 126800,
      rating: 4.9,
      courseCount: 5,
    },
    {
      id: "gu-shen",
      name: "顾深",
      title: "摄影指导 · 灯光设计",
      avatar: "instructors/gu-shen.jpg",
      bio: "一台灯讲一个谎。顾深把审讯室、急诊廊和夜戏 praticles 拆成可复用的布光配方，适合独立制作与 AI 短剧预演。",
      students: 94800,
      rating: 4.7,
      courseCount: 4,
    },
    {
      id: "ye-cheng",
      name: "叶澄",
      title: "编剧 · 故事架构",
      avatar: "instructors/ye-cheng.jpg",
      bio: "前网文责编，现短剧总编剧。课程覆盖钩子、反转、人物欲望线，以及如何把 70 集大纲收成 8 集也能看完的骨架。",
      students: 210600,
      rating: 4.8,
      courseCount: 5,
    },
  ];

  function lectures(prefix, titles, start, previewCount, dramaAt) {
    return titles.map((title, i) => ({
      id: `${prefix}-l${i + 1}`,
      title,
      durationSec: 480 + ((start + i * 73) % 420),
      source:
        dramaAt === i
          ? { kind: "drama-engine", url: DRAMA }
          : { kind: "video", url: VIDEOS[(start + i) % VIDEOS.length] },
      isPreview: i < previewCount,
    }));
  }

  function sections(prefix, main, extras, start, dramaAt) {
    return [
      { id: `${prefix}-s1`, title: "正片", lectures: lectures(prefix, main, start, 1, dramaAt) },
      { id: `${prefix}-s2`, title: "幕后与精讲", lectures: lectures(`${prefix}x`, extras, start + 6, 0, -1) },
    ];
  }

  function reviews(seed, texts) {
    return texts.map((content, i) => ({
      id: `r${seed}-${i}`,
      userName: NAMES[(seed + i) % NAMES.length],
      rating: i === 2 ? 4 : 5,
      date: `2026-0${(seed % 6) + 1}-${10 + i * 5}`,
      content,
    }));
  }

  const drafts = [
    {
      id: "c-rooftop", slug: "rooftop-last-cigarette", title: "天台·最后一支烟",
      subtitle: "雨停之前，谁先开口。一部 8 集都市夜戏，把告别拍成呼吸。",
      description: "她在天台抽完最后一支烟。城市还亮着，人已经决定离开。本片以近景与雨声为骨架，适合学习夜戏调度、对白留白，以及如何用一场天气完成人物弧光。正片完整可看，幕后附导演分镜精讲。播放源已预留 Drama Engine 接口，后续可替换为生成成片。",
      cover: "covers/rooftop.jpg", poster: "posters/rooftop.jpg", category: "urban",
      tags: ["夜戏", "都市", "告别", "雨"], instructorId: "lin-yan",
      price: 128, originalPrice: 268, rating: 4.8, ratingCount: 21420, students: 48620,
      lastUpdated: "2026-08", bestseller: true,
      main: ["雨停之前", "最后一支烟", "谁先开口", "楼下的灯", "未接来电", "天亮以后"],
      extras: ["夜戏布光配方", "雨戏走位与安全", "对白里的停顿"], v: 1, dramaAt: 3,
      reviewTexts: ["天台风和雨声处理得很好，近景不腻。当成短剧看也很完整。", "林晏讲调度很具体，不是空谈氛围。", "希望能再出一个白天对照版。"],
    },
    {
      id: "c-standin", slug: "seven-days-standin", title: "替身夫人的七日",
      subtitle: "合同签了七天。第七天清晨，谁还记得签名的人。",
      description: "豪门、替身、限时契约——短剧最熟悉的骨架，用表演把“假的”演成真的。苏晚带你看眼神何时该躲，何时必须对上。适合学习人物关系的进与退，以及奢侈空间里的走位。",
      cover: "covers/standin.jpg", category: "mansion",
      tags: ["豪门", "替身", "契约", "表演"], instructorId: "su-wan",
      price: 148, originalPrice: 298, rating: 4.7, ratingCount: 15880, students: 39210,
      lastUpdated: "2026-07", hot: true,
      main: ["合同第一夜", "餐桌上的座位", "谁在叫错名字", "花园里的证人", "第六日反转", "七日黎明"],
      extras: ["近景对视训练", "奢侈空间走位", "替身角色的秘密"], v: 2, dramaAt: 3,
      reviewTexts: ["楼梯那场戏光影漂亮，表演克制。", "把爽文桥段拍出了难堪，很难得。", "有两集节奏偏快，但整体值。"],
    },
    {
      id: "c-rebirth", slug: "reborn-ninety-nine", title: "重生九十九次",
      subtitle: "同一扇门，第九十九次推开。这一次他把那句话咽了回去。",
      description: "重生短剧容易变成说明书。叶澄用“欲望线不重置”的办法，让每一次回来都带着上一世的伤。适合编剧学习钩子密度、信息控制，以及如何在 8 集里完成命运感。",
      cover: "covers/rebirth.jpg", poster: "posters/rebirth.jpg", category: "rebirth",
      tags: ["重生", "命运", "编剧", "反转"], instructorId: "ye-cheng",
      price: 168, originalPrice: 328, rating: 4.9, ratingCount: 30112, students: 67240,
      lastUpdated: "2026-08", bestseller: true,
      main: ["第一次死亡", "门后的水", "改掉的那句话", "平行的午饭", "第九十八次", "留下的人"],
      extras: ["钩子密度表", "信息控制练习", "结局的三种收法"], v: 3, dramaAt: 5,
      reviewTexts: ["大纲课比正片还过瘾，直接能用在自己本子上。", "重生桥段终于不像读档游戏。", "希望补充反派欲望线专章。"],
    },
    {
      id: "c-raincafe", slug: "third-cup-of-rain", title: "雨声停在第三杯",
      subtitle: "窗玻璃上的水，比他们先把话说完。一部免费的安静恋爱。",
      description: "没有霸总，没有误会三年。只有一间通宵咖啡店、三杯美式，和两个人把雨听完。适合学习生活流短剧如何把“没事发生”拍成有事发生。",
      cover: "covers/raincafe.jpg", category: "urban",
      tags: ["恋爱", "生活流", "对白", "免费"], instructorId: "su-wan",
      price: 0, rating: 4.6, ratingCount: 8904, students: 121300,
      lastUpdated: "2026-06", level: "beginner",
      main: ["第一杯，不加糖", "雨变大了", "第三杯凉了", "店员换班", "伞只剩一把", "晴天打烊"],
      extras: ["生活流的事件密度", "窗边布光", "沉默的剪辑点"], v: 4, dramaAt: 3,
      reviewTexts: ["终于有一部不靠误会推进的恋爱短剧。", "适合睡前看，雨声像白噪音。", "结局有点淡，但淡得诚实。"],
    },
    {
      id: "c-interro", slug: "rose-in-the-box", title: "审讯室里的玫瑰",
      subtitle: "一朵不该出现的花，一次不该开始的问询。",
      description: "顾深把审讯室当成舞台：一盏顶光、一扇百叶窗、一朵玫瑰。刑侦短剧最容易吵，这部选择把音量拧小。适合学习单空间调度、灯光说谎，以及如何让观众站在“不该站的一边”。",
      cover: "covers/interrogation.jpg", category: "suspense",
      tags: ["刑侦", "单空间", "灯光", "悬疑"], instructorId: "gu-shen",
      price: 158, originalPrice: 288, rating: 4.8, ratingCount: 11240, students: 22180,
      lastUpdated: "2026-07", level: "intermediate",
      main: ["玫瑰被放上桌", "她不看镜头", "第一次改口", "录音停了", "窗外有人", "结案报告"],
      extras: ["顶光与百叶窗", "单空间调度图", "声音作为证据"], v: 5, dramaAt: 3,
      reviewTexts: ["布光课能直接搬到自己的夜戏。", "玫瑰这个道具用得很狠。", "有一集推理跳跃，但氛围满分。"],
    },
    {
      id: "c-palace", slug: "embroidered-intent", title: "锦绣谋心",
      subtitle: "灯火再长，也照不见袖中的折子。",
      description: "古装权谋短剧常被服装淹没。林晏把走廊当时间轴，用灯的远近写权力。适合学习群像站位、服化与场面的主次，以及如何让一句“臣妾知罪”真正有重量。",
      cover: "covers/palace.jpg", poster: "posters/palace.jpg", category: "palace",
      tags: ["古装", "权谋", "群像", "场面"], instructorId: "lin-yan",
      price: 188, originalPrice: 368, rating: 4.9, ratingCount: 27650, students: 54110,
      lastUpdated: "2026-08", bestseller: true,
      main: ["宫灯初上", "袖中折子", "谁先低头", "夜宴的座位", "雨打琉璃", "殿门开了"],
      extras: ["走廊即时间轴", "群像站位", "服化不抢戏"], v: 6, dramaAt: 3,
      reviewTexts: ["比很多院线古装还干净。", "权谋不靠旁白，全靠站位，学到了。", "希望出续集：后宫白天戏。"],
    },
    {
      id: "c-intern", slug: "midnight-shift", title: "实习生的零点档",
      subtitle: "最后一盏台灯，决定她明天还在不在这栋楼。",
      description: "职场逆袭不靠金句，靠一次改过的表格和一次没发出去的邮件。叶澄把办公室拍成夜戏，教你写“小人物的杠杆”。适合学习当代职场短剧的真实感。",
      cover: "covers/intern.jpg", category: "office",
      tags: ["职场", "逆袭", "现实主义"], instructorId: "ye-cheng",
      price: 99, originalPrice: 199, rating: 4.5, ratingCount: 7340, students: 19880,
      lastUpdated: "2026-05", newest: true, level: "beginner",
      main: ["入职第一周", "被改掉的表格", "零点档", "谁关的灯", "邮件撤回", "工牌还在"],
      extras: ["职场潜台词", "办公室 praticles", "小人物杠杆"], v: 7, dramaAt: 3,
      reviewTexts: ["看完想把工位收拾一下。", "没有霸总，全是具体的活，真实。", "节奏前松后紧，能接受。"],
    },
    {
      id: "c-star", slug: "please-sign-the-galaxy", title: "星河请签收",
      subtitle: "他们躺在屋顶，把整条银河当成未读消息。",
      description: "浪漫不一定要告白。苏晚把“看星星”拍成一场不说话的对手戏。适合学习外景夜戏、身体轴线，以及如何让风景给人物让路。",
      cover: "covers/starfield.jpg", category: "urban",
      tags: ["浪漫", "外景", "青春"], instructorId: "su-wan",
      price: 88, originalPrice: 168, rating: 4.7, ratingCount: 6540, students: 24320,
      lastUpdated: "2026-06",
      main: ["为什么上屋顶", "手机先没电", "银河过中天", "她侧过身", "流星没人许愿", "下楼的时候"],
      extras: ["外景夜戏曝光", "身体轴线", "风景不抢人"], v: 8, dramaAt: 3,
      reviewTexts: ["星空不是壁纸，是第三个人。", "很适合和对象一起看。", "有点短，意犹未尽。"],
    },
    {
      id: "c-mask", slug: "mask-and-contract", title: "假面与合同",
      subtitle: "他在玻璃上的倒影，比本人先承认。",
      description: "总裁短剧的脸谱很容易塌。林晏选择半张脸藏在阴影里，用合同条款当潜台词。适合学习人物造型、权力感的镜头语言，以及如何避免油腻。",
      cover: "covers/maskceo.jpg", category: "mansion",
      tags: ["总裁", "契约", "镜头语言"], instructorId: "lin-yan",
      price: 138, originalPrice: 258, rating: 4.6, ratingCount: 12110, students: 30880,
      lastUpdated: "2026-04", level: "intermediate",
      main: ["合同第三款", "半张脸", "谁先松领带", "夜会取消", "倒影先承认", "签名处空白"],
      extras: ["权力感的镜头", "避免油腻的总裁", "阴影里的信息"], v: 9, dramaAt: 3,
      reviewTexts: ["这版总裁不油，值回票价。", "合同当潜台词这个方法我直接抄了。", "女主戏份可以再多一点。"],
    },
    {
      id: "c-oldtown", slug: "town-has-no-secret", title: "古镇没有秘密",
      subtitle: "巷子会记住脚步。雾散之前，有人已经走丢。",
      description: "江南水乡是天然的迷宫。顾深用晨雾和石板反光做线索，把探案写成迷路。适合学习外景连续空间、雾的曝光，以及如何让风景成为证人。",
      cover: "covers/oldtown.jpg", category: "suspense",
      tags: ["探案", "古镇", "雾", "空间"], instructorId: "gu-shen",
      price: 118, originalPrice: 228, rating: 4.7, ratingCount: 5420, students: 15440,
      lastUpdated: "2026-03",
      main: ["第一声脚步", "灯还亮着", "桥下的回声", "谁喂了猫", "巷子分叉", "雾散之后"],
      extras: ["雾的曝光", "连续空间剪辑", "风景即证人"], v: 10, dramaAt: 3,
      reviewTexts: ["古镇拍得不像旅游宣传片，好。", "空间感很强，像能走进去。", "凶手动机稍弱，画面补上了。"],
    },
    {
      id: "c-live", slug: "livestream-accident", title: "直播间心动事故",
      subtitle: "麦还开着。她说错的那句，被三万人听完。",
      description: "竖屏时代最吵的空间：直播间。苏晚把 RGB 灯和弹幕当成对手，表演课直接在近景里打。适合学习竖屏构图、即兴与真实感，以及如何把“人设崩了”写成戏。",
      cover: "covers/livestream.jpg", category: "urban",
      tags: ["竖屏", "直播", "喜剧", "近景"], instructorId: "su-wan",
      price: 79, originalPrice: 159, rating: 4.5, ratingCount: 9870, students: 41220,
      lastUpdated: "2026-08", hot: true, newest: true,
      main: ["开播倒计时", "说错的那句", "弹幕停了一秒", "下播之后", "谁剪了切片", "第二次开播"],
      extras: ["竖屏近景", "即兴与真实", "人设崩塌的写法"], v: 11, dramaAt: 3,
      reviewTexts: ["太真实了，像我同事。", "竖屏构图讲得很实用。", "喜剧点可以再密一点。"],
    },
    {
      id: "c-north", slug: "northern-pact", title: "北境白约",
      subtitle: "雪不认人情。契约写在冰上，春天会反悔。",
      description: "奇幻短剧最贵的是世界。林晏用一片雪原和一匹马，把契约拍成天气。适合学习史诗感的极简做法、外景冷色，以及如何让奇幻不空洞。",
      cover: "covers/northsnow.jpg", poster: "posters/northsnow.jpg", category: "fantasy",
      tags: ["奇幻", "契约", "史诗", "极简"], instructorId: "lin-yan",
      price: 198, originalPrice: 398, rating: 4.8, ratingCount: 8640, students: 18770,
      lastUpdated: "2026-02", level: "expert",
      main: ["第一场雪", "马上的人", "契约三行", "冰裂了", "谁先回头", "春天的悔"],
      extras: ["史诗感的极简", "冷色外景", "奇幻不空洞"], v: 12, dramaAt: 2,
      reviewTexts: ["一张马、一片雪，比很多特效片有世界。", "适合想拍奇幻又没预算的人。", "设定可以再交代一点。"],
    },
    {
      id: "c-campus", slug: "unfinished-yearbook", title: "未完成的毕业照",
      subtitle: "相框还空着一个位置。阳光很好，人没有到齐。",
      description: "校园短剧容易甜腻。叶澄把毕业季写成一次缺席。免费课程，适合入门学习群像、金晖外景，以及如何让“青春”不只是滤镜。",
      cover: "covers/campus.jpg", category: "campus",
      tags: ["校园", "毕业", "群像", "免费"], instructorId: "ye-cheng",
      price: 0, rating: 4.6, ratingCount: 14320, students: 88940,
      lastUpdated: "2026-07", newest: true, level: "beginner",
      main: ["集合迟到", "空着的位置", "谁不肯笑", "金晖过了", "冲洗店", "补拍那天"],
      extras: ["群像调度", "金晖外景", "青春不只滤镜"], v: 13, dramaAt: 3,
      reviewTexts: ["看完把大学相册又翻了一遍。", "免费但完整，入门刚好。", "有点克制，不够哭，但这是优点。"],
    },
    {
      id: "c-er", slug: "night-shift-er", title: "急诊夜班",
      subtitle: "廊灯是冷的。有一扇门后面，是热的。",
      description: "医疗短剧最怕表演喊。顾深把走廊拍成呼吸机的节奏，让职业动作代替台词。适合学习冷暖对比、职业剧的身体逻辑，以及如何拍“救人”而不煽。",
      cover: "covers/hospital.jpg", category: "urban",
      tags: ["医疗", "职业", "夜戏"], instructorId: "gu-shen",
      price: 108, originalPrice: 208, rating: 4.7, ratingCount: 4210, students: 13220,
      lastUpdated: "2026-04", level: "intermediate",
      main: ["交班", "3:12 的铃", "那扇热的门", "手套的声音", "谁先坐下", "天亮交出去"],
      extras: ["冷暖对比", "职业动作", "不煽的救人"], v: 14, dramaAt: 3,
      reviewTexts: ["走廊的灯太准了。", "医生走位像真的上过班。", "希望有日班对照。"],
    },
    {
      id: "c-sea", slug: "unread-by-the-sea", title: "海边未读",
      subtitle: "风很大。屏幕亮了一下，又暗了。",
      description: "一部几乎没有对白的短剧。苏晚让海风替他们说话。适合学习情绪外景、空镜的功能，以及如何把手机当成角色。",
      cover: "covers/coastal.jpg", category: "urban",
      tags: ["情绪", "外景", "极简对白"], instructorId: "su-wan",
      price: 68, originalPrice: 128, rating: 4.4, ratingCount: 3180, students: 17650,
      lastUpdated: "2026-01",
      main: ["风先到", "屏幕亮了一下", "未读两封", "潮水过来", "他把手机扣上", "回城的车"],
      extras: ["空镜功能", "手机当角色", "外景风声"], v: 15, dramaAt: 3,
      reviewTexts: ["很短，像一首诗。", "对白少反而更难受。", "如果再长两集就好了。"],
    },
    {
      id: "c-parallel", slug: "letter-from-the-other-side", title: "平行世界的回信",
      subtitle: "同一条街，两种天气。她把信寄给了另一边的自己。",
      description: "平行世界是短剧特效预算的黑洞。叶澄用一条马路的左右各拍一遍，把“如果”写成剪辑问题。适合学习对照蒙太奇、服装连续性，以及低成本的世界分叉。",
      cover: "covers/parallel.jpg", category: "rebirth",
      tags: ["平行", "剪辑", "低成本特效"], instructorId: "ye-cheng",
      price: 158, originalPrice: 298, rating: 4.8, ratingCount: 10110, students: 26440,
      lastUpdated: "2026-08", hot: true, level: "expert",
      main: ["分界线", "左边在下雨", "右边的回信", "两次早餐", "谁先过马路", "同一扇门"],
      extras: ["对照蒙太奇", "服装连续性", "低成本分叉"], v: 16, dramaAt: 4,
      reviewTexts: ["一条马路拍出两个世界，聪明。", "剪辑课非常值。", "设定解释可以更早一点。"],
    },
  ];

  const COURSES = drafts.map((d) => ({
    id: d.id,
    slug: d.slug,
    title: d.title,
    subtitle: d.subtitle,
    description: d.description,
    cover: d.cover,
    poster: d.poster,
    category: d.category,
    tags: d.tags,
    language: "zh",
    level: d.level || "all",
    instructorId: d.instructorId,
    price: d.price,
    originalPrice: d.originalPrice,
    rating: d.rating,
    ratingCount: d.ratingCount,
    students: d.students,
    lastUpdated: d.lastUpdated,
    bestseller: !!d.bestseller,
    hot: !!d.hot,
    newest: !!d.newest,
    whatYouLearn: LEARN,
    requirements: ["一副耳机", "对故事有耐心", "不需要专业器材"],
    includes: ["点播视频", "分场提要", "终身观看", "手机与电脑"],
    sections: sections(d.id, d.main, d.extras, d.v, d.dramaAt ?? 3),
    reviews: reviews(d.v, d.reviewTexts),
  }));

  global.VELORA = { CATEGORIES, INSTRUCTORS, COURSES, DRAMA };
})(window);
