import * as T from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {buildHeritageScene,buildAssetScene,bridgeDeckHeight} from './heritage-renderer.mjs';
import {getAsset} from './heritage-assets.mjs';
import {footprint,pointInPolygon} from './heritage-maps.mjs';
const colors={'民居':0x7b8072,'街市':0xab9273,'宫殿':0xc49a42,'门墙':0x9a6250,'桥梁':0xd9d3be,'舟车':0x685b47,'植物':0x728763,'园林':0x90936d,'人物':0x56585b,'附属':0xc0b6a0};
function dispose(g){if(!g)return;const gs=new Set(),ms=new Set();g.traverse(n=>{if(n.geometry)gs.add(n.geometry);if(n.material)(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>ms.add(m));});gs.forEach(x=>x.dispose());ms.forEach(x=>x.dispose());g.removeFromParent();}
function planScene(map){const g=new T.Group(),mat=new T.MeshBasicMaterial({color:0xddd4c0}),ground=new T.Mesh(new T.PlaneGeometry(map.bounds.width,map.bounds.depth),mat);ground.rotation.x=-Math.PI/2;g.add(ground);
 for(const water of map.water){const s=new T.Shape();water.points.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();const m=new T.Mesh(new T.ShapeGeometry(s),new T.MeshBasicMaterial({color:0x719f98}));m.rotation.x=-Math.PI/2;m.position.y=.02;g.add(m);}
 const records=new Map(),add=(color,x,z,w,d,rotation,y=.1)=>{if(!records.has(color))records.set(color,[]);records.get(color).push({x,z,w,d,rotation,y});};
 for(const r of map.roads)for(let n=1;n<r.points.length;n++){const a=r.points[n-1],b=r.points[n];add(0xc9beaa,(a[0]+b[0])/2,(a[1]+b[1])/2,Math.hypot(b[0]-a[0],b[1]-a[1]),r.width,Math.atan2(b[1]-a[1],b[0]-a[0]),.05);}
 for(const w of map.walls)add(0x985b48,(w.x1+w.x2)/2,(w.z1+w.z2)/2,Math.hypot(w.x2-w.x1,w.z2-w.z1),w.thickness,Math.atan2(w.z2-w.z1,w.x2-w.x1),.13);
 for(const i of map.instances){if(getAsset(i.assetId).category==='附属')continue;add(colors[getAsset(i.assetId).category]||0x888277,i.x,i.z,i.w,i.d,i.rotation,.2);}
 for(const [color,items]of records){const m=new T.InstancedMesh(new T.BoxGeometry(1,.04,1),new T.MeshBasicMaterial({color}),items.length),o=new T.Object3D();items.forEach((i,n)=>{o.position.set(i.x,i.y,i.z);o.scale.set(i.w,1,i.d);o.rotation.y=-i.rotation;o.updateMatrix();m.setMatrixAt(n,o.matrix);});g.add(m);}return g;}
export class HeritageView{
 constructor(container){this.container=container;this.mode='3d';this.onSelect=null;this.paused=false;this.alive=true;this.map=null;this.preview=null;this.size=100;this.time=0;this.flatZoom=1;this.flatOffset={x:0,z:0};this.events=[];
 try{this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.65));this.renderer.setClearColor(0xebe7db);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.canvas=this.renderer.domElement;container.append(this.canvas);this.scene=new T.Scene();this.scene.add(new T.HemisphereLight(0xfff5e1,0x8c907a,2));this.sun=new T.DirectionalLight(0xffedcf,2.8);this.sun.position.set(-300,900,550);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.bias=-.0004;this.sun.shadow.normalBias=.25;this.scene.add(this.sun);this.camera=new T.PerspectiveCamera(38,1,.5,50000);this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.maxPolarAngle=Math.PI*.49;this.controls.minPolarAngle=.1;this.controls.minDistance=8;this.controls.maxDistance=20000;this.controls.screenSpacePanning=true;this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.hit=new T.Vector3();this.ground=new T.Plane(new T.Vector3(0,1,0),0);this.selection=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial({color:0xa8c098,transparent:true,opacity:.28,depthWrite:false}));this.selection.visible=false;this.scene.add(this.selection);
 this.listen('webglcontextlost',e=>{e.preventDefault();this.paused=true;container.dispatchEvent(new CustomEvent('view-error',{detail:'三维上下文已中断，请刷新恢复。'}));});
 }catch(e){this.renderer?.dispose();this.renderer?.domElement.remove();this.renderer=null;this.canvas=document.createElement('canvas');container.append(this.canvas);this.ctx=this.canvas.getContext('2d');this.fallbackReason='当前设备无法开启 WebGL，已显示可缩放的二维布局。';this.mode='top';}
 this.canvas.style.touchAction='none';this.listen('pointerdown',e=>{this.press={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};if(!this.renderer)this.canvas.setPointerCapture?.(e.pointerId);});
 this.listen('pointermove',e=>{if(!this.press||this.renderer)return;const dx=e.clientX-this.press.lastX,dz=e.clientY-this.press.lastY;this.press.lastX=e.clientX;this.press.lastY=e.clientY;if(Math.hypot(e.clientX-this.press.x,e.clientY-this.press.y)>6)this.press.moved=true;this.flatOffset.x-=dx/(this.flatScale||1);this.flatOffset.z-=dz/(this.flatScale||1);this.draw2d();});
 this.listen('pointerup',e=>{if(this.press&&!this.press.moved&&Math.hypot(e.clientX-this.press.x,e.clientY-this.press.y)<6)this.pick(e);this.press=null;});this.listen('pointercancel',()=>this.press=null);
 if(!this.renderer)this.listen('wheel',e=>{e.preventDefault();this.flatZoom=Math.max(.5,Math.min(60,this.flatZoom*Math.exp(-e.deltaY*.002)));this.draw2d();},{passive:false});
 this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.resize();let previous=performance.now();const frame=now=>{if(!this.alive)return;this.raf=requestAnimationFrame(frame);const dt=Math.min(.05,(now-previous)/1000);previous=now;if(this.renderer){this.controls.update();if(!this.paused&&!document.hidden&&this.mode==='3d'&&!this.preview)this.animate(dt);this.renderer.render(this.scene,this.camera);}};this.raf=requestAnimationFrame(frame);
 }
 listen(name,fn,options){this.canvas.addEventListener(name,fn,options);this.events.push([name,fn,options]);}
 clear(){dispose(this.group);dispose(this.lots);this.group=null;this.lots=null;this.walkers=[];if(this.selection)this.selection.visible=false;}
 setCity(map){this.clear();this.map=map;this.preview=null;this.size=Math.max(map.bounds.width,map.bounds.depth);if(this.renderer){this.group=buildHeritageScene(map);this.scene.add(this.group);this.lots=planScene(map);this.scene.add(this.lots);this.makeWalkers();}this.setMode(this.mode);this.fit();}
 makeWalkers(){const segments=this.map.roads.flatMap(r=>r.points.slice(1).map((b,n)=>({a:r.points[n],b})));this.walkers=(this.group.userData.motionNodes||[]).map((node,n)=>{let best,dist=Infinity;for(const seg of segments){const dx=seg.b[0]-seg.a[0],dz=seg.b[1]-seg.a[1],len=Math.hypot(dx,dz),t=Math.max(0,Math.min(1,((node.position.x-seg.a[0])*dx+(node.position.z-seg.a[1])*dz)/(len*len))),d=Math.hypot(node.position.x-seg.a[0]-dx*t,node.position.z-seg.a[1]-dz*t);if(d<dist){dist=d;best={...seg,len,t};}}return {node,...best,speed:.85+(n%5)*.12,direction:n%2?1:-1,phase:n};}).filter(w=>w.a);}
 animate(dt){this.time+=dt;for(const w of this.walkers||[]){w.t+=dt*w.speed/w.len*w.direction;if(w.t>1){w.t=1;w.direction=-1;}if(w.t<0){w.t=0;w.direction=1;}const x=w.a[0]+(w.b[0]-w.a[0])*w.t,z=w.a[1]+(w.b[1]-w.a[1])*w.t;w.node.position.set(x,bridgeDeckHeight(this.map,x,z),z);w.node.rotation.y=Math.atan2((w.b[0]-w.a[0])*w.direction,(w.b[1]-w.a[1])*w.direction);for(const n of w.node.children)if(n.name.startsWith('leg-')||n.name.startsWith('arm-'))n.rotation.x=Math.sin(this.time*7+w.phase)*(n.name.endsWith('left')?1:-1)*.19;}}
 setMode(mode){if(!['3d','top','lots'].includes(mode))return;this.mode=this.renderer?mode:mode==='3d'?'top':mode;if(this.controls){this.controls.enableRotate=this.mode==='3d';if(this.group)this.group.visible=this.mode!=='lots'||!!this.preview;if(this.lots)this.lots.visible=this.mode==='lots'&&!this.preview;this.fit();}else this.draw2d();}
 setPaused(v){this.paused=!!v;}
 fit(){this.flatZoom=1;this.flatOffset={x:0,z:0};if(!this.renderer){this.draw2d();return;}const box=this.group?new T.Box3().setFromObject(this.group):new T.Box3(new T.Vector3(-50,0,-50),new T.Vector3(50,10,50)),center=box.getCenter(new T.Vector3()),extent=box.getSize(new T.Vector3());if(!this.preview)center.set(0,0,0);this.controls.target.copy(center);const span=Math.max(this.size,extent.x,extent.z,extent.length()*.45);const dist=(span*.7)/Math.tan(this.camera.fov*Math.PI/360);const direction=this.mode==='3d'?new T.Vector3(this.preview?.8:.48,1.02,1.32).normalize():new T.Vector3(0,1,.0001);this.camera.position.copy(center).add(direction.multiplyScalar(this.mode==='3d'?dist:span*2.15));this.camera.near=Math.max(.25,span*.001);this.camera.far=Math.max(5000,span*20);this.controls.minDistance=Math.max(6,span*.05);this.controls.maxDistance=span*9;this.camera.lookAt(center);this.camera.updateProjectionMatrix();this.fitBox=box;this.resize();this.controls.update();
 const r=span*.75;Object.assign(this.sun.shadow.camera,{left:-r,right:r,top:r,bottom:-r,near:1,far:span*6});this.sun.position.set(-span*.5,span*1.7,span);this.sun.shadow.camera.updateProjectionMatrix();}
 resize(){const w=Math.max(1,this.container.clientWidth||600),h=Math.max(1,this.container.clientHeight||500);if(this.renderer){this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}else{const ratio=Math.min(globalThis.devicePixelRatio||1,2);this.canvas.width=w*ratio;this.canvas.height=h*ratio;this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';this.draw2d();}}
 focusLandmark(id){const l=this.map?.landmarks.find(l=>l.id===id);if(!l)return;if(this.preview)this.setCity(this.map);if(this.renderer){const target=new T.Vector3(l.x,0,l.z),dir=this.camera.position.clone().sub(this.controls.target).normalize(),close=this.map.id==='qingming-scroll'?220:260;this.controls.target.copy(target);this.camera.position.copy(target).add(dir.multiplyScalar(close));this.camera.updateProjectionMatrix();this.controls.update();}else{this.flatOffset={x:l.x,z:l.z};this.flatZoom=4;this.draw2d();}const i=this.map.instances.find(i=>l.instanceIds.includes(i.id));this.select(i||null);}
 previewAsset(assetId,params={}){const a=getAsset(assetId);if(!a)throw new RangeError('未知资源');this.clear();this.preview=assetId;this.previewParams={...a.defaultSize,...params};this.size=Math.max(this.previewParams.w,this.previewParams.d,this.previewParams.h)*1.25;if(this.renderer){this.group=buildAssetScene(assetId,params);this.scene.add(this.group);this.mode='3d';this.controls.enableRotate=true;this.fit();}else{this.flatZoom=1;this.draw2d();}}
 pick(e){if(!this.map||this.preview)return;const r=this.canvas.getBoundingClientRect();let x,z;if(this.renderer){this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);if(!this.ray.ray.intersectPlane(this.ground,this.hit))return;x=this.hit.x;z=this.hit.z;}else{x=(e.clientX-r.left-r.width/2)/(this.flatScale||1)+this.flatOffset.x;z=(e.clientY-r.top-r.height/2)/(this.flatScale||1)+this.flatOffset.z;}const hits=this.map.instances.filter(i=>pointInPolygon([x,z],footprint(i))).sort((a,b)=>(getAsset(a.assetId).category==='附属')-(getAsset(b.assetId).category==='附属')||a.w*a.d-b.w*b.d);this.select(hits[0]||null);}
 select(i){if(this.selection){this.selection.visible=!!i;if(i){this.selection.position.set(i.x,.3,i.z);this.selection.scale.set(i.w,.55,i.d);this.selection.rotation.y=-i.rotation;}}this.onSelect?.(i);}
 draw2d(){if(!this.ctx)return;const c=this.ctx,r=Math.min(globalThis.devicePixelRatio||1,2),w=this.canvas.width/r,h=this.canvas.height/r;c.setTransform(r,0,0,r,0,0);c.fillStyle='#ebe7db';c.fillRect(0,0,w,h);
 if(this.preview){const a=getAsset(this.preview),p=this.previewParams,s=Math.min(w/p.w,h/p.d)*.7;c.fillStyle='#'+(colors[a.category]||0x9b8b71).toString(16);c.fillRect(w/2-p.w*s/2,h/2-p.d*s/2,p.w*s,p.d*s);c.fillStyle='#354439';c.font='14px sans-serif';c.fillText(a.label+' · '+p.w+' × '+p.d+' m 占地',16,30);c.fillText('二维回退：单体三维造型需要 WebGL',16,h-18);return;}
 if(!this.map)return;const s=Math.min(w/this.map.bounds.width,h/this.map.bounds.depth)*.92*this.flatZoom;this.flatScale=s;c.save();c.translate(w/2-this.flatOffset.x*s,h/2-this.flatOffset.z*s);c.scale(s,s);const polygon=(points,color)=>{c.fillStyle=color;c.beginPath();points.forEach(([x,z],i)=>i?c.lineTo(x,z):c.moveTo(x,z));c.closePath();c.fill();};for(const p of this.map.plazas){c.fillStyle='#d2c9b5';c.fillRect(p.x-p.w/2,p.z-p.d/2,p.w,p.d);}for(const a of this.map.water)polygon(a.points,'#719f98');for(const r of this.map.roads){c.strokeStyle='#c9beaa';c.lineWidth=r.width;c.beginPath();r.points.forEach(([x,z],i)=>i?c.lineTo(x,z):c.moveTo(x,z));c.stroke();}for(const wall of this.map.walls){c.strokeStyle='#965944';c.lineWidth=wall.thickness;c.beginPath();c.moveTo(wall.x1,wall.z1);c.lineTo(wall.x2,wall.z2);c.stroke();}for(const i of this.map.instances)polygon(footprint(i),'#'+(colors[getAsset(i.assetId).category]||0x888277).toString(16));c.restore();c.fillStyle='#53604e';c.font='12px sans-serif';c.fillText(this.map.id==='forbidden-city'?'N ↑ · 北':'画卷从右至左展开',16,25);}
 destroy(){this.alive=false;cancelAnimationFrame(this.raf);this.observer?.disconnect();this.controls?.dispose();this.clear();this.selection?.geometry.dispose();this.selection?.material.dispose();for(const [n,f,o]of this.events)this.canvas.removeEventListener(n,f,o);this.renderer?.dispose();this.canvas?.remove();}
}
